### ISSUE TITLE
freeing the smaller of two merged shapes causes heap corruption

### ISSUE THREAD

**Issue by DoubleCouponDay** [DoubleCouponDay/Chunkus#53]
from drmemory.exe

      
      Error #124: INVALID HEAP ARGUMENT to free 0x0000023df0d68280
      # 0 replace_free                     [D:\a\drmemory\drmemory\common\alloc_replace.c:2710]
      # 1 merge_shapes
      # 2 enlarge_shape
      # 3 find_shapes 
      # 4 fill_quadrant
      # 5 libwinpthread-1.dll!?           +0x0      (0x00007ffad862823d <libwinpthread-1.dll+0x823d>)
      # 6 msvcrt.dll!beginthreadex        +0x133    (0x00007ffb0436dfb4 <msvcrt.dll+0x3dfb4>)
      # 7 msvcrt.dll!endthreadex          +0xab     (0x00007ffb0436e08c <msvcrt.dll+0x3e08c>)
      # 8 ntdll.dll!RtlUserThreadStart
      Note: @0:02:33.032 in thread 16276
      Note: next higher malloc: 0x0000023df0d682f0-0x0000023df0d71170
      Note: memory was previously freed here:
      Note: # 0 replace_free                [D:\a\drmemory\drmemory\common\alloc_replace.c:2710]
      Note: # 1 merge_shapes
      Note: # 2 enlarge_shape
      Note: # 3 find_shapes 
      Note: # 4 fill_quadrant
      Note: # 5 libwinpthread-1.dll!?      +0x0      (0x00007ffad862823d <libwinpthread-1.dll+0x823d>)

**Comment by DoubleCouponDay** [comment]
the offending code

    if(smaller){
        free(smaller);
    }

**Comment by sjsushi3d** [comment]
fixed in 94526841cb9975ad03187e49256bfedcae02feea
